version: '3.9'

services:
  redis:
    container_name: redis_server
    image: redis:latest
    command: [ "redis-server", "/etc/redis/redis.conf", "--bind", "0.0.0.0" ]
    volumes:
      - ./authen-service/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  redis_data:

